### ISSUE TITLE
DO NOT USE THIS SEED GENERATOR!!!

### ISSUE THREAD

**Issue by Danyu-Wu** [lancekrogers/iota_seed_generator#1]
It will cause security problem if any body using this seed generator to generate your IOTA seed!
  The main reason is that the seed which generated by function "seed_gen" is a float, only has about 10^17 of pricision, and all the 81 characters of IOTA seed dependent on this float, so the randomness of the IOTA seed has been degradated severely!
  To solve this problem, I suggest that DO NOT use the random.seed() function, and perform a random delay before each character generation of the 81-loops.

**Comment by lancekrogers** [comment]
This script was updated to use the new secrets module provided in Python 3.6.  This module uses your system's random generator instead of using the random modules pseudo random generator.  This should address any security concerns associated with the randomness of this generator.
